### ISSUE TITLE
Quell "Can't access to your password" dialog when gpg-card is not inserted

### ISSUE THREAD

**Issue by alclary** [passff/passff#101]
This is less of an actual _issue_ with the program and more of me seeking help on a customization. What are my options to disable the "Can't access to your password, Please add your passphrase to gpg-agent first" pop-up dialog which is initiated on pages on which passff auto-fills information. This message is only initiated when my gpg-card (containing my gpg-keys) is not plugged in. Is there a way to completely quell this dialog? Perhaps a conditional bash script would be possible if I knew how passff called upon and/or passed information to gpg-agent? Any idea where to start?

Thank you for any assistance or suggestions.

**Comment by jvenant** [comment]
Currently there is no way to disable the dialog box. I will add an option to do that because I'm agree with you : most of the time it is annoying.
The dialog box appear if the sentence "gpg: decryption failed: No secret key" is found in the gpg/pass error output. So waiting for a new version including the new option, the only workaround I can see is to wrap the pass call in a script that would replace the sentence in something else or that would redirect the error output to dev/null.

**Comment by tuxor1337** [comment]
Closed by #248
