### ISSUE TITLE
Allow tuning of auto fill match technique

### ISSUE THREAD

**Issue by hwine** [passff/passff#124]
Being able to tune the url matching used for autofill could be a workaround to #122 

In this case (AWS login), the query parameters of the URL contain the post-authentication URL, which would distinguish AWS from Kindle activity. Yeah - likely requires a regexp input, which has it's hazards, but I suspect most users of this extension will be quite technical.

**Comment by oneirosFade** [comment]
This might also help with #127

**Comment by Ivan0xFF** [comment]
I would really appreciate this. Being able to matching by URL "field" instead of file name would be great. You can do it in pass by doing: `pass grep --regexp="url: .*my.url.com\b.*"`

**Comment by jvenant** [comment]
this would require a decryption of the entire password repository. I'd like to avoid that. That's why the url matching is entirely based on the file names

**Comment by jmdavis** [comment]
@jvenant Wait, what's the deal with the "Fields" tab in the plugin GUI then? It specifically talks about taking the data from inside the passwords repository and lets you tweak the field names to look for. And that includes the URL field. So, if the matching is done entirely based on the file names, what's the point of that tab?

And personally, the plugin is pretty much useless to me if it's not looking at the URLs inside the files. The file names I've selected frequently don't match the URLs (which may be why the plugin often does such a poor job selecting the right entry). I've even considered picking gibberish names for the files so that it's that much less obvious what they go with, since unfortunately, the file names are not encrypted. If they were, it would be reasonable to use a site like github or bitbucket to hold your password repo, but with the names out in the open like that, it really isn't IMHO. I'm certainly not interested in having the files names match the exact URLs that they go with. That's what the url field in the pass files is for.

So, I'd consider it a _must_ to actual look into the files for the url field. If you want to make that configurable, that's fine with me, but as it is, the plugin does such a horrible job of matching passwords for me (and it's been getting worse) that it's getting to the point that it's doing more harm than good. I've been seriously considering removing it, because it so frequently picks the wrong entry now, and too often, I hit enter before I realize that it's wrong and end up submitting the wrong username/password combo to the site.

**Comment by phryneas** [comment]
@jmdavis you're using the wrong tool for the job then - pass itself is not suited for your use case.

In your case, checking inside 200 password files would mean spawning 200 shell processes which each execute gpg a few times. This would take too much time and resources. 
And many of us are power users with many more passwords, counting myself at 450, so it would slow to a crawl.
Also at some time, all your passwords would reside in memory, as all these decrypted files would need to be parsed.
Neither of this is desirable.

**Comment by jvenant** [comment]
Hi @jmdavis,
Thank you for your feedback.
* The url field is used for the "goto" features
* To Decrypt the entire password repository is just not an option. Sorry for that.

Maybe it could be a good idea to have some kind of unique global metadata.gpg file using the standard multiline format and doing the link between a password file and an url (and eventually to store some other repository metadata). This way, I would have to only decrypt one file without any password inside. You could try to suggest this to the [pass mailing list](https://lists.zx2c4.com/mailman/listinfo/password-store) as an addition to the Data Organization section. So it would become a "best practice" about how to store repository metadata.
Johan

**Comment by phryneas** [comment]
just as a heads up: such a mapping file has been suggested a few dozen times in the two years I've been reading the mailing list.
nobody there thinks that it is a good idea.

if you do not trust your git repo, you can use something like https://github.com/joeyh/git-remote-gcrypt/
if you do not trust your local hard drive, you can either encrypt your full disk or the folder with your password-store-repo

**Comment by jmdavis** [comment]
Well, then clearly PassFF isn't going to do what I want, and I'll have to stick to running pass on the command line to get the passwords, as desirable as it may be to have a plugin do it for you.

@phryneas The issue really isn't my local storage. The issue is that while it would be very useful to be able to stick my password repo up somewhere like github or bitbucket so that I can easily grab it as well as sync between devices, that means putting my password files out in the open (even if the repo is private, employees of the company running the site could get access to it), and that means that which places I have passwords for would be out in the open, which is unacceptable. Maybe the git-remote-gcrypt project that you linked to would help with that. I'll have to check it out.

I honestly wish that pass put everything in one file and then left the rest of the UI the same (including stuff like the edit command). It would hide the list of what you have passwords for, and it would make it so that programs like PassFF would only have to decode one file. But it would have the downside of not working with multiple gpg keys like you can do now (though I suppose that that could be done by having a file per gpg key, though in the extreme case, you're back to where we are now). But that's a big enough shift that I don't expect that it'll ever happen except maybe if someone forked pass.

**Comment by jvenant** [comment]
You could 
* Disable PassFF autofill feature and search your repository manually using the shortcut
* Or you could also use the rofi/rofi-pass/xdotool combo

**Comment by tuxor1337** [comment]
I don't get the essential idea of this issue from the first post and the discussion in the following posts is only confusing me more and more. I would even say that there are several ideas discussed here. Therefore, I suggest that, whoever has a specific request covered in this issue, opens a new issue with a clear description of his request (pointing to this issue for reference).
