### ISSUE TITLE
How secure is mozilla’s extension model (and passff within it)?

### ISSUE THREAD

**Issue by svictor9** [passff/passff#215]
Hi, and thanks for developping this extension!
 I’m new to using `pass`, and I was thinking of using `passff` in firefox. I installed it, it works fine and seems very convenient.
Then I read [this post by Chris Knutson](https://medium.com/@canuteson/stop-installing-firefox-extensions-c0840ed10da0). It’s really about the (in)security of Mozilla’s extension model, but it explicitly takes `passff` as an example. As far as I understand, the problem would not be `passff` itself but another extension making a call to passff and hence gaining access to the variables and objects within it
I’m just an average not-too-techie linux user, unable to verify the accuracy of that post. Does it make sense to you?

**Comment by tuxor1337** [comment]
Thanks for your question!

Security definitely is an issue for us and we have ongoing discussions about security related design decisions such as #194. However, you are not the first person to ask for a statement on this and so I would like to forward you to my (general) statement here: https://github.com/passff/passff/issues/190#issuecomment-292721489

Now for Chris Knutson's analysis: The flaws that he addressed in his 2016 article do not apply to the current version of PassFF since it's based on the WebExtensions framework (which has the sandboxing feature). Furthermore, those flaws generally do not apply to Firefox versions 57 (scheduled for Nov. 2017) and up. However, he is definitely correct about using extensions from untrusted sources. And, as I stated in my post linked above, browsers and browser technology are "traditionally" very prone to security issues of all kinds and you should be extremely careful when using things like password managers inside your browser.

**Comment by svictor9** [comment]
Thanks for explaining this! I’m glad to know that the issue in Chris’s article does not apply any more to passff.
