### ISSUE TITLE
OSX: Host application might need to be installed as root

### ISSUE THREAD

**Issue by ysim** [passff/passff#219]
I'm running Firefox 54.0.1 on OSX 10.11.6. I recently went through the steps outlined in the documentation, and kept getting this error whenever I tried [re]installing the extension or starting up Firefox:

> Error executing pass script
>
> Component returned failure code: 0x80520006
> (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST)
> [nslFile.isExecutable]

From the rest of the documentation, I saw that the "appropriate location" for the json file should be in `/Library/...`, even though the installer installs it into the home directory, so I tried creating the necessary directories there`/Library/Application Support/Mozilla/NativeMessagingHosts`, and then symlinked `passff.json` over from `~/Library/Application Support/Mozilla/NativeMessagingHosts/`, and then everything started working. 

I see in the installer that it already checks if it's being run by root, and if so, installs it into `/Library/...`. If it seems reasonable to you, I'd be happy to open a PR to amend the documentation, either in the main `README.md` (under "Issues"), or in `docs/INSTALLATION.md`, to suggest running the installer as root / prefix `sudo` to the installer command as it's an easy fix.

**Comment by stankec** [comment]
I'm having the exact same problem as you did though I can't get the extension to work.

I'm running `FirefoxDeveloperEdition 55.0b14` on `macOS 10.12.6`. I'm installing from source - I pulled the repo, switched to the master branch and did the following:

```Bash
cd src/host
sudo ./install_host_app.sh --local firefox
ln -s /Library/Application\ Support/Mozilla/NativeMessagingHosts/passff.json /Users/stanko/Library/Application\ Support/Mozilla/NativeMessagingHosts/passff.json
cd ..
make
```

Then I fired up Firefox (through Finder) and installed the addon from the file that was build in the `bin` directory of the repo. Though, whenever I try to use the addon I get the following:

<img width="457" alt="screen shot 2017-08-03 at 21 30 00" src="https://user-images.githubusercontent.com/1655218/28939849-f5901070-7892-11e7-9a05-244fadede49a.png">

And the debug log is empty...

@ysim how /where from did you install the addon?

**Comment by stankec** [comment]
Hm... Just tried to open Firefox through the terminal by running

```Bash
./Applications/FirefoxDeveloperEdition.app/Contents/MacOS/firefox
```

Suddenly the addon started working... I guess I'm experiencing a problem with FF55 sandboxing.

**Comment by tuxor1337** [comment]
Any news on this?

**Comment by mddvul22** [comment]
I'm a multi-platform passff users.  I've using the new version on two Linux workstations.  And I'm trying to get it working on MacOS.  One question I'm not clear about in this bug report: if I install the host app as root on the Mac, which passff add-on version am I supposed to be using with it?  The older 0.1.30 release?  Or the version 1.0 versions that say they are only for Linux?  Or another version somewhere else?

Thanks!

**Comment by tuxor1337** [comment]
I think it would be best to test with the newest version from https://github.com/passff/passff/releases

**Comment by mddvul22** [comment]
Well, I've been unsuccessful today.  I'm using the 1.0 release.  And I've installed the host app as root, and as an unprivileged user.  I've also installed it to both places at the same time.  I've not had any success any of these ways.  I've attempted both "through shell" and "direct call".  I've verified that I have python3 installed.  So, I don't know what the problem is.   Clicking on the pass icon, results in:

"Sorry, an unexpected error occured. Make sure your preferences are correctly set and that the native host app is installed."

When debugging it, I get the following:

Runtime port has crashed: Error: Could not establish connection. Receiving end does not exist.  main.js:16:7
	logPrototype moz-extension://2acf0fae-ae05-fa42-8706-7818a0425238/modules/main.js:16:7
	PassFF.bg_exec/< moz-extension://2acf0fae-ae05-fa42-8706-7818a0425238/modules/main.js:157:7

Error restoring menu : TypeError: menu_state is undefined
Stack trace:
PassFF.Menu.init/<@moz-extension://2acf0fae-ae05-fa42-8706-7818a0425238/modules/menu.js:24:1
  main.js:16:7

**Comment by vizv** [comment]
Hi all, I had the same issue days ago and I have made it works.

Assuming you install pass with brew like I did.

So the problem is when the Firefox launches the host app, `PATH` doesn't pass in correctly and some command line utilities used by `pass` cannot be found. So I have created a wrapper for `pass` which exports `PATH` environment variables.

**Comment by mddvul22** [comment]
@vizv can you please provide the details of your wrapper script?  Thanks!

**Comment by vizv** [comment]
@mddvul22 

This is what I have:

```bash
#!/usr/bin/env bash

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

exec /usr/local/bin/pass "$@"
```

**Comment by stankec** [comment]
@vizv  I've tried out your wrapper but I still can't get it to work :/
Perhaps you can check what I did wrong.

I copied your script above to `/usr/local/bin/pass-ff` and did `chmod +x /usr/local/bin/pass-ff` to make it executable (I've tried to run it manually by calling `pass-ff`, and it works as expected).

Then I configured the extensions like this:
<img width="549" alt="screen shot 2017-10-28 at 10 48 44" src="https://user-images.githubusercontent.com/1655218/32132936-a6fa9a42-bbcd-11e7-9527-e5464a2e2595.png">

But I still get the following error:
<img width="474" alt="screen shot 2017-10-28 at 10 49 46" src="https://user-images.githubusercontent.com/1655218/32132944-c4d9fe22-bbcd-11e7-9dbe-97cb8b7ec1e4.png">

Just to note. I'm running the latest release on `master` since I'm on FF57.

**Comment by vizv** [comment]
@stankec well, mine works:

![screen shot 2017-10-28 at 10 11 21 am](https://user-images.githubusercontent.com/1577163/32136773-c1f43448-bbc8-11e7-9b05-f953d0fea8fe.png)

The version of Firefox I have:

![screen shot 2017-10-28 at 10 12 49 am](https://user-images.githubusercontent.com/1577163/32136774-c261a910-bbc8-11e7-978d-5e89b4bd24c7.png)

And config:

![screen shot 2017-10-28 at 10 13 02 am](https://user-images.githubusercontent.com/1577163/32136775-c2a4a60c-bbc8-11e7-8731-03dd313044a4.png)

Note I have a non-standard password store directory, so I set the `PASSWORD_STORE_DIR`:

```bash
#!/usr/bin/env bash

# password store directory
export PASSWORD_STORE_DIR=~/Repositories/All/viz-pass

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

exec /usr/local/bin/pass "$@"
```

Moreover, I didn't use master branch. Instead I directly installed from [Firefox Add-on Page](https://addons.mozilla.org/en-US/firefox/addon/passff/) and did a trick (run `document.querySelector('div.install-wrapper a').classList.remove('linux');` in the browser console) to enable it.

**Comment by stankec** [comment]
I managed to get it to work. The problem was that the preferences changes weren't reflected in real-time. I had to disable and enable the extension, after setting the desired preferences.

**Conclusion:**
There is no need to install the host app as root, the only problem there is is that the host's app `PATH` variable is being set to the wrong value by the extension itself. This can be seen if you log incoming requests to the host app, in the `environment` field the value of `PATH` is `/usr/bin:/bin:/usr/sbin:/sbin`. @vizv  's solution is a functional workaround for this issue.

**Suggestion/Possible fix:**
* Figure out why [this code](https://github.com/passff/passff/blob/e17b88b0cddb7c347171d8cd5b89b9eda667b429/src/modules/preferences.js#L35) doesn't correctly detect macOS (or at least it's actions don't get reflected in the preferences) and add an action to override the default path sent by the extension.
* Add a preference to edit the PATH manually instead of assuming it

**Steps taken to get it working:**
1. Uninstall the extension and remove everything from the user's and system NativeMessagingHosts directory
2. Install the latest PassFF version from the Firefox Add-on Page using the trick @vizv  described in the post above.
3. Install the host application using [the original guide](https://github.com/passff/passff/blob/master/docs/INSTALLATION.md#installing-the-host-application) but use version `1.0.3linux` instead of `1.0.0` (chaned in the URL)
3. In `/usr/local/bin/` create a new file called `passff-pass` (it's important that it ends with `pass`) with the contents of the script from @vizv  from above (without the `PASSWORD_STORE_DIR` line)
5. Go to Pass preferences and under the `Pass script` tab set the following:
  * `User home` value to the return value of `echo $HOME`
  * `Pass command` to `/usr/local/bin/passff-pass`
  * `Pass store dir` to your pass store directory usually the return value of `echo $HOME/.password-store`
6. Go back to the Add-ons page
7. Disable passff
8. Enable passff

**Steps taken to detect the issue:**
* Added the following to he host app's code:
  ```Python
  import os, sys, json, struct, subprocess, re, random, string
  
  def randomword(length):
     return ''.join(random.choice(string.ascii_lowercase) for i in range(length))

  reqid = randomword(6)

  def logout(direction, msg):
      with open('/Users/stanko/Desktop/passff.log', 'a') as file:
          file.write(direction)
          file.write(" [")
          file.write(reqid)
          file.write("] - ")
          file.write(msg)
          file.write("\n")
  ```
* Modified the `getMessage` method:
  ```Python
  rawLength = sys.stdin.buffer.read(4)
  if len(rawLength) == 0:
      sys.exit(0)
  messageLength = struct.unpack('@I', rawLength)[0]
  message = sys.stdin.buffer.read(messageLength).decode("utf-8")
  logout("RECEIVED", message) # <-- THIS
  return json.loads(message)
  ```
* Used `tail -f ~/Desktop/passff.log` to track requests

**Comment by vizv** [comment]
For those who want to install the current version on macOS,
**use this URL to install directly**: https://addons.mozilla.org/firefox/downloads/file/721365/passff-1.0.3linux-an+fx-linux.xpi

> ~~Moreover, I didn't use master branch. Instead I directly installed from [Firefox Add-on Page](https://addons.mozilla.org/en-US/firefox/addon/passff/) and did a trick (run `document.querySelector('div.install-wrapper a').classList.remove('linux');` in the browser console) to enable it.~~

This method above is not working anymore.

**Comment by jwiegley** [comment]
I can confirm that with the above steps, I was able to get things working OS X 10.12.6 and FF 57.0.1.

**Comment by vizv** [comment]
Today I decided to upgrade passff to the latest version (1.0.7linux) for my macOS and I managed to get it to work.

Basically passff won't work for macOS is because PATH is not set correctly when Firefox launches, which results a) NativeMessagingHosts script won't work since python3 cannot be found, and b) pass script requires command getopt which cannot be executed correctly.

To solve these issues, an shell wrapper for pass was created to set PATH env, and here is the new method:

1. make sure `python3` is installed with `brew install python3`
2. make sure `pass` is installed with `brew install pass`
3. Install host app with `curl -sSL https://github.com/passff/passff/releases/download/1.0.7linux/install_host_app.sh | bash -s -- firefox`
4. Edit `~/Library/Application Support/Mozilla/NativeMessagingHosts/passff.py`, change the first line to `#!/usr/local/bin/python3`
5. Install version 1.0.7 with https://addons.mozilla.org/firefox/downloads/file/822606/passff-1.0.7linux-an+fx-linux.xpi
6. In add-on preference, set environment variables:
```
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PASSWORD_STORE_DIR=/path/to/password-store-dir
```
7. Disable and enable passff add-on and you should be able to use it without shell wrapper for pass

> Tested on Firefox 58.0b13, macOS High Sierra 10.13.2, passff-1.0.7linux

**Comment by tuxor1337** [comment]
@vizv Thanks for your investigations! I'm wondering: If you set the PATH variable explicitely, shouldn't python3 be found by `/usr/bin/env` so that it's not necessary to change the shebang in `passff.py`?

**Comment by vizv** [comment]
@tuxor1337 The path is set for the plugin, after host script been launched. I tried leaving shebang as `#!/usr/bin/env python3` and it crashes without giving me reason (and I think it's because when Firefox launches on macOS, it didn't have the right PATH).

`/usr/local/bin/pass` might be the default value, however I use my own wrapper before this update.

**Comment by tuxor1337** [comment]
Okay, that means we probably have to modify the host application on the fly at install time injecting the right shebang in the install script - this shouldn't be too hard.

**Comment by vizv** [comment]
`sed -i '1c#!/usr/local/bin/python3' "$HOME/Library/Application Support/Mozilla/NativeMessagingHosts/passff.py"` should do the work (I didn't test it though)

**Comment by tuxor1337** [comment]
Would somebody please confirm that the latest commits fix #188 and this issue and finally restore full OS X compatibility for PassFF?

**Comment by vizv** [comment]
@tuxor1337 the latest version doesn't work yet, since tag `1.0testing` didn't release and `HOST_URL` or `MANIFEST_URL` are not found.

**Comment by tuxor1337** [comment]
Oh, of course there's no release before I have confirmation that this version is working. However, testing is still possible when building from source and using the install script's `--local` option:

    git clone https://github.com/passff/passff
    cd passff/src
    make
    cd ../bin/1.0testing
    ./install_host_app.sh --local firefox

The addon file for installation in Firefox is then located in `passff/bin/1.0testing/passff.xpi`. I hope somebody with OS X can test this because I don't have access to a Mac computer.

**Comment by vizv** [comment]
Before I try your method, I `cd` to `~/Library/Application Support/Mozilla` and `mv` my currently working `NativeMessagingHosts` to `NativeMessagingHosts.old`.

Then I tried your method, and the first time it gives me:
```
Python 3 executable located at /usr/local/bin/python3
Installing Firefox host config
cp: cannot stat '/tmp/passff/bin/1.0testing/passff.json': No such file or directory
```

So I copied the `passff.json` from the latest release and the error was gone.

Then I did a `diff -Naur NativeMessagingHosts.old NativeMessagingHosts` and no output is shown which means the updated `install_host_app.sh` works as expected.

I didn't install the `passff.xpi` from the build result and 1.0.7linux works with current host script (since they are identical) with my current add-on settings.

**Comment by tuxor1337** [comment]
Cool, thanks for testing! I forgot copying passff.json in the build script. This is fixed in the latest commit.

**Comment by mddvul22** [comment]
Many thanks to everybody who worked to get this working!!!

I was able to get version 1.1 working today with @vizv notes in this thread.  I tried using the instructions found here: https://github.com/passff/passff/blob/master/docs/INSTALLATION.md#installing-the-host-application but I got the following error:

"$ curl -sSL https://github.com/passff/passff/releases/download/1.1/install_host_app.sh | bash -s -- firefox
Python 3 executable located at /usr/local/bin/python3
Installing Firefox host config
sed: 1: "/Volumes/Data/Users/cib ...": extra characters at the end of D command"

So, what worked for me was:
1. manually downloading the files to their proper location in:
~/Library/Application Support/Mozilla/NativeMessagingHosts
2. Make sure that passff.py is executable.
3. Manually set the shebang in passff.py to: #!/usr/local/bin/python3
4. Change the addon settings location to pass to /usr/local/bin/pass
5. Add the variables to the addon settings:
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PASSWORD_STORE_DIR=/Location/to/.password-store
6. Disable/Enable the addon.

Not sure what the sed error is about.  I don't know python.  But I thought I'd pass it along.

Thanks again!

**Comment by vizv** [comment]
@mddvul22 may I know how did you install your `pass` under macOS?

**Comment by mddvul22** [comment]
Vizv's notes about Environment variables needing to be set, should be added to the addon page instructions, when the addon is installed in Firefox.  I believe that currently, though I might be mistaken, that the only mention of the Environment Variables for mac users is in these bug reports.

**Comment by tuxor1337** [comment]
On Mac, the environment variables are set by default like proposed here once this pull request can be accepted: https://github.com/passff/passff/pull/267 Currently, I'm waiting for further reviews from Mac users about that pull request. In any case, that pull request will be included in the next version of PassFF.

**Comment by deton8** [comment]
@mddvul22 Thank you, after hours of trying it finally worked (Mac OSX High Sierra with Firefox 58.0.2) following your description.
 I have one Trick to add for the install script to work.
The following changes to the "install_host_app.sh" will fix the sed error:

/////comment out line 112 like this:

# Replace path to host
#sed -i -e "s/PLACEHOLDER/$ESCAPED_HOST_FILE_PATH/" "$MANIFEST_FILE_PATH"

/////add this code:

if [ $(uname -s) == 'Darwin' ]; then
  # Replace path to python3 executable
  /usr/bin/sed -i '' "1 s@.*@#\!${PYTHON3_PATH}@" "$HOST_FILE_PATH"
  # Replace path to host
  /usr/bin/sed -i '' -e "s/PLACEHOLDER/$ESCAPED_HOST_FILE_PATH/" "$MANIFEST_FILE_PATH"
else
  # Replace path to python3 executable
  sed -i "1c#\!${PYTHON3_PATH}" "$HOST_FILE_PATH"
  # Replace path to host
  sed -i -e "s/PLACEHOLDER/$ESCAPED_HOST_FILE_PATH/" "$MANIFEST_FILE_PATH"
fi


continue with step 3. from mddvul22  above
