### ISSUE TITLE
Pale Moon support?

### ISSUE THREAD

**Issue by DirtYiCE** [passff/passff#224]
I don't think this suggestion will have much chance given that development moved to webextensions, but is it possible that we would get a version that works with Pale Moon? I'd like to avoid the disaster called firefox 57, and this is like the only essetial firefox addon that doesn't work on Pale Moon.

I've checked out the last non web extension version from git, it look's like `modules/CustomizableUI.jsm` doesn't exists on Pale Moon so the plugin doesn't even load. I've tried to search for it, there's this code from ublock
https://github.com/gorhill/uBlock/blob/b429e1c7bad8d891f83f9f282a8406952caedbcd/platform/firefox/vapi-background.js#L2766
but it's a lot of code for someone who has zero experience with mozilla addon development.

**Comment by tuxor1337** [comment]
Personally, I'm not going to keep working on non-WebExtensions versions of PassFF. I never seriously worked on XUL-extensions. So I'm definitely lacking the competence. Apart from that, I have doubts that it's a good idea to write a security based add-on like a password manager in the XUL framework where add-ons are not sandboxed so that one add-on can access the data another add-on is handling.
