### ISSUE TITLE
"Copy login" / "Copy password" do not work when GPG requires password

### ISSUE THREAD

**Issue by waweber** [passff/passff#233]
I am on: Firefox 55.0.3 x64 on Fedora 26 running KDE, running pass 1.7.1 and passff 1.0.3linux.

When selecting "Copy login" or "Copy password" from the passff menu, if the GPG key must be unlocked, the requested field is not copied to the clipboard after completing unlocking. It works correctly if unlocking is not required.

To reproduce:

1. Restart gpg-agent so nothing is in the keyring
2. Go to the passff menu and select "Copy login" or "Copy password" for any entry
3. gpg-agent should open a window asking for the password for your GPG key
4. Enter your password, adding the key to the keyring
5. Attempt to paste your login/password from the clipboard
6. Observe that this works as expected after trying again, once the key is in the keyring. Also, notice that repeating these steps with "Fill" instead of copy successfully fills the information after unlocking the keyring; the issue is limited only to copying

Expected behavior: the login/password should be copied into the clipboard

**Comment by mddvul22** [comment]
As another point of reference, I'm having similar problems with the copy login/copy password.  I'm using Firefox 52.4 (ESR). Pass version 1.6.5. and passff 1.0.3linux.

In my case, copy login and copy password don't ever work.  It doesn't matter whether gpg-agent is restarted or not.  If I select copy login or copy password, gpg-agent will open up, and ask for my gpg key.  I provide it, but the usename and/or password is not placed into the copy/paste buffer.  When I paste what is is the copy/paste buffer, it pastes whatever I had in the buffer before I was interacting with passff.

**Comment by tuxor1337** [comment]
The copy feature is a bit buggy, because it requires the PassFF popup to stay open until the pass script has been executed. If a GPG popup forces the PassFF popup to close, we "lose connection" so that the output of the pass script gets lost. This is because I write to the clipboard in the popup Javascript. Probably, we can fix this by moving the clipboard code to the background script as in this example: https://github.com/mdn/webextensions-examples/blob/master/context-menu-copy-link-with-types/background.js

**Comment by kpocius** [comment]
It's even worse with Firefox Quantum - if the keyring isn't unlocked, trying to copy the password or login crashes the browser.
