### ISSUE TITLE
Does not gracefully handle missing pinentry gui

### ISSUE THREAD

**Issue by waweber** [passff/passff#246]
Firefox 57, Fedora 4.13.12-300.fc27.x86_64, passff 1.0.3linux

To reproduce:
  - Set up an environment with Firefox, pass, passff, etc. installed.
  - Ensure pinentry is installed, but pinentry-gtk or pinentry-qt are missing (no graphical pinentry programs)
  - Attempt to use passff
  - Observe the browser and/or desktop busy-wait

Expected behaviour:
  - An error message is displayed

**Comment by shtrom** [comment]
Busy wait sounds like #243 (fixed by #248)

**Comment by tuxor1337** [comment]
Ah, sounds reasonable. 

@waweber: It would be helpful, if you could check out the latest version from Github, run `make` from within the `src` subdirectory and test with the generated `passff.xpi` in the `bin` subdirectory. There's some chance that your problem is fixed (or at least the behavior should be changed).

**Comment by tuxor1337** [comment]
@waweber Would you please test with the latest version (1.0.4linux) from addons.mozilla.org and report back if this issue still applies?
