### ISSUE TITLE
Wrong submit button chosen

### ISSUE THREAD

**Issue by madduck** [passff/passff#252]
On [the Handelsblatt login page](https://profil.vhb.de/sso/login?service=http://www.handelsblatt.com/ajaxentry/nocache/ssohandshake?redirecturl=http://finanzen.handelsblatt.com/redirect.htn?e=1%26url=https://www.handelsblatt.com/), if I let PassFF "fill and submit", then it picks the "lost password" link at the bottom, rather than the big login button.

Maybe this is because both of those buttons have `type=submit` in the HTML, and PassFF just picks the last element?

I'm unsure whether changing that "heuristic" is going to fix things, though if I had to bet money right now on whether it's better to choose the first or the last of several `type=submit` buttons, then I'd probably go for the first, instead of the last.

A better approach would probably be to store in the password record an identifier that should then allow PassFF to pick the right button to submit, probably in a way similar to #61…

**Comment by tuxor1337** [comment]
In a very recent commit (https://github.com/passff/passff/commit/de70745d9919d3fd41667b6236c8771812351817#diff-e8d31f21df475f877ac2881d2336da60) this behaviour has been changed to choose the first instead of the last submit button in the form. This would fix this particular case, but - as you say - you might still run into trouble on pages where the order is different.

**Comment by madduck** [comment]
How amazing. I just tried `HEAD` and can confirm that the new behaviour solves this issue. Thanks a lot.
