### ISSUE TITLE
Missing support for htaccess auth

### ISSUE THREAD

**Issue by tampakrap** [passff/passff#27]
passff is ignoring htaccess authentication dialogs. No idea how easy this is to implement, but it would be great to have it

**Comment by einalex** [comment]
keefox somehow hooks into the htaccess dialogs so it should be possible

**Comment by denydias** [comment]
Oh! It's great there is already an issue for this. I'm was trying to make it work, but now I know it's not implemented. +1 for this as an enhancement.

**Comment by ReAzem** [comment]
+1! I keep running into this issue.

BTW thanks for the awesome plugin @jvenant

**Comment by jvenant** [comment]
I'm agree : obviously, It's a must have.
But my hope is that implementing #46 will indirectly solve this.

**Comment by denydias** [comment]
I thought so, @jvenant. Thanks for the hands up.

**Comment by shtrom** [comment]
:+1:

**Comment by shtrom** [comment]
There also appears to be an issue with the SocialAPI share box. Clicking anywhere else, including on the PassFF button, kills the window before one could log in. (I have the problem with wallabag/wallabag).

**Comment by tuxor1337** [comment]
Is there any hope that this can be implemented using the WebExtensions API?

**Comment by michaelgerlachreservix** [comment]
Sorry for bumping - But Basic HTTPAuth is still not working ATM..

**Comment by n3ph** [comment]
Sorry for bumping this, but Basic HTTPAuth is still not working..
Is there any way to accomplish this as #46 is obsolete since the whole rewrite of the WebExtensions API..

**Comment by tuxor1337** [comment]
Once the HTTPAuth dialog has opened, PassFF cannot interfere. The only way to step in is *before* the HTTPAuth dialog opens: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/onAuthRequired

Therefore, my suggestion would be: Whenever a web page requires an HTTPAuth, we step in and tell the user that she can now either choose an entry from his password store or manually input her credentials. For users who generally don't use PassFF for HTTPAuth, this would be annoying so that we should probably make this an optional thing.

**Comment by varac** [comment]
Awesome, thx! This nice feature deserves a release ;)
