### ISSUE TITLE
Firejail issues

### ISSUE THREAD

**Issue by wyager** [passff/passff#284]
Hello all,

I'm trying to get passff configured with firejail.

After adding `.config/firejail/firefox.profile` with contents

```
include /etc/firejail/firefox.profile
whitelist ${HOME}/.password-store
```

Passff can *list* my saved passwords, but attempting to fill any of them does nothing.  I don't see any generated log messages. Any ideas?

**Comment by wyager** [comment]
OK, got it. I also had to add "noblacklist" and "whitelist" entries for .gnupg.

I don't think this could reasonably be considered a problem with passff, but it does seem like there should be a better way to do this than carte-blanche giving firefox permission to look at gpg key data.

I also wish passff logging was more usable - I ended up modifying passff.py to write to syslog to figure out what was going on.

I'm closing the issue because, but up to y'all if you want to figure out a way to make this work by default.

**Comment by b-misc** [comment]
I'm stuck with apparently the same or at least a similar problem:
passff seems to work if I start Firefox without firejail
passff doesn't work if I start Firefox within firejail. Adding the lines mentioned above didn't solve the problem for me, there seems to be also a "blocking" due to gpg-agent:

If I try to do firejail --profile=/etc/firejail/firefox.profile pass <my.testsite.org> I'm prompted for the key's password by pinentry-qt. I can enter it and then pass will show my respective password; then the command keeps blocking, i.e. the command doesn't finish, I have to use Ctrl+C.
After killing, I'm prompted for the password again, so gpg-agent doesn't seem to be able to keep it.
Executing pass directly (without firejail) works correctly, including gpg-agent's caching.

Anyone with any hints, how to proceed?

**Comment by b-misc** [comment]
Just found the reason: python is blacklisted by disable-interpreters.inc
Adding noblacklist entries for python solved the issue.
