### ISSUE TITLE
Wrong handling of symlinked directories

### ISSUE THREAD

**Issue by madduck** [passff/passff#299]
Consider two sites, `userprofile.example.org` and `someservice.example.com`, which share their credentials. To avoid redundancy in the data, I simply made a symlink in the `~/.password-store` Git repo from `someservice.example.com` to `userprofile.example.org`.

In my case, the sites are `aspsms.com` and `smsblaster.com`…

In the `pass` tree output, this symlink is properly displayed:

```
% pass
[…]
├── smsblaster.com -> aspsms.com/  [recursive, not followed]
[…]
```

and `pass` has no issue therewith:

```
% pass smsblaster.com/username | sha256sum
395a3838d1882f5e86de5d40465189399fca1acbae9e55b239f736c2b9c6547c  -
% pass aspsms.com/username | sha256sum
395a3838d1882f5e86de5d40465189399fca1acbae9e55b239f736c2b9c6547c  -
```

However, `PassFF` doesn't like it. For `aspsms.com`, it displays the credentials properly, but on `smsblaster.com`, I just see `smsblaster.com` (not `smsblaster.com/username`), and if I fill in the login form with these data, the password will just be "smsblaster.com", rather than the actual password.

**Comment by tuxor1337** [comment]
I'm marking this as an incompatibility of PassFF with symlinked directories. Note that symlinked entries are fine because symlink notes of the pass output is ignored completely: https://github.com/passff/passff/blob/master/src/modules/pass.js#L264

There is no guarantee that it's possible for PassFF to resolve the link from the information given in the output of pass (for example, if the symlink is pointing to an absolute path or to a location outside the password-store directory). Hence, the most elegant solution would be to make note of all symlinks and call `pass smsblaster.com` separately to get information about the subtree. However, it would be necessary to make sure that we don't end up in a recursion loop if the linked directory contains a link to the original directory containing the link...

**Comment by tuxor1337** [comment]
By the way, I'm wondering, why tree doesn't follow the symlink if it's in the same directory as the linked directory. Does anybody have an explanation for this? I don't see how this could possible cause a recursion?!
