### ISSUE TITLE
Reload causes text to be appended to open Etherpads

### ISSUE THREAD

**Issue by madduck** [passff/passff#332]
Yeah, so this is funny… if I hit the reload button in the PassFF toolbar menu (as I just did right now, when it was displaying my github details), it then also appends the following to *every open Etherpad instance*:

```        
          $
github.com/madduck$
          $
$
          $
$
        $
      $
```

The `$` characters denote line-endings and are not part of the text appended, but I included them to illustrate the whitespace.

This is weird, but could also be pretty bad, you know, imagine I was working on a document with folks, and then chose to take a break on some site I wouldn't want the world to know I used; Especially because Etherpad actually keeps track of edits.

**Comment by tuxor1337** [comment]
I cannot reproduce this with PassFF 1.3 on the official Etherpad demo page on https://demo.sandstorm.io/appdemo/h37dm17aa89yrd8zuqpdn36p6zntumtv08fjpu8a8zrte7q1cn60

Which version of PassFF are you using? Which OS, and which version of Firefox? Which version of Etherpad are you using? How can we reproduce this?

**Comment by madduck** [comment]
I am using PassFF compiled from 1e90c3f25d62a0b8070647c373e20dd820eec549 on Firefox 60 (on Linux, Debian unstable).

Can you reproduce this problem on e.g. https://pad.riseup.net/p/0KFiXYrTZJTf . It certainly happens to me on Sandstorm.

And it also happens with all other add-ons disabled. Fun!

**Comment by tuxor1337** [comment]
This is related to PassFF's input field popup menu. For the popup menu to be embedded into pages, we have to modify the DOM: We create a `<div class="passff_popup_menu">` as a child of `<body>` and put the menu entries there. Etherpad, on the other hand, listens to all DOM changes and interprets PassFF's popup `<div>` as the result of a copy-paste user action (see also https://www.reddit.com/r/javascript/comments/caje9/how_to_keep_track_of_user_content_changes_made_to/). That's why Etherpad ends up appending the contents of PassFF's popup to the text area.

Unfortunately, I have no idea how to work around this. If you are concerned about privacy, you should deactivate the popup feature (that's under preferences) for now. But note that it's only with commit a7fcaa40941245b9fe53494fa1266e036024c031 that this option starts to behave as expected.

By the way, this is also a privacy issue for any other web page that uses JavaScript. Since we are modifying the DOM the page's JavaScript can detect those changes and have the contents of the PassFF popup sent to a server etc. Maybe we can work around this by embedding our stuff into iframes?

**Comment by tuxor1337** [comment]
Commit 79c8093 fixes this. It's wrapping the popup into an iframe, solving the problem of exposing the list of matching items.

**Comment by madduck** [comment]
Fantastic analysis, and thanks for the speedy fix, @tuxor1337. It's fixed now, indeed! *thumbsup*
