### ISSUE TITLE
Copy login / Copy password does nothing

### ISSUE THREAD

**Issue by treyssatvincent** [passff/passff#368]
### General information.
I use pass with login as filename with only the password as content

- Versions
  - Operating system: Archlinux (latest)
  - Browser: Firefox 62
  - PassFF: 1.5.1
  - Host app: 1.0.2

Javascript console output : 
`[PassFF.content] Message Page.copyToClipboard received in content`

---

### Actual behavior
pasff fills in the connection forms correctly but when I click `Copy password` or `Copy login` it does not fill the clipboard.

### Expected behavior
When `Copy password` or `Copy login` is clicked it should fill the clipboard.

### Steps to reproduce the behavior
1. Click Copy password or Copy login on passff
2. Try to paste it anywhere

**Comment by 5bentz** [comment]
Hello treyssatvincent,

Thanks for the report!

I use host app v1.0.3 (not yet released) and Debian Testing.

### I can reproduce on some webpages, and not some others

#### I can reproduce on
- about:debugging
- about:newtab
- https://addons.mozilla.org/en-US/firefox/?utm_source=discovery.addons.mozilla.org&utm_medium=firefox-browser&utm_content=find-more-link-top&src=api

#### I cannot reproduce on
- facebook.com
- google.com

### When I can reproduce, I have this error
```
[PassFF.background] Message Menu.onCopyToClipboard received in background util.js:36:9
...
[PassFF.background] Executing Page.copyToClipboard in content script
[PassFF.background] Content script port has crashed: Error: "Could not establish connection. Receiving end does not exist."
	content_exec moz-extension://.../modules/util.js:138:18
```
It crashes in util.js, line 138:
```
          return browser.tabs.sendMessage(tab.id, {
            action: action,
            params: args,
            useSender: false
          });
```

### Content scripts
I have just seen this on https://github.com/mdn/webextensions-examples/tree/master/beastify

> it's not possible to inject content scripts into certain pages, including privileged browser pages like "about:debugging" and the addons.mozilla.org website. If the user clicks the beastify icon when such a page is loaded into the active tab, the popup displays an error message.

### Fix
So, I have turned page.js 's `copyToClipboard` into a *background_function*. It seems to do the trick. 

```
diff --git a/src/modules/page.js b/src/modules/page.js
index d1b4fac..dd740f5 100644
--- a/src/modules/page.js
+++ b/src/modules/page.js
@@ -819,7 +819,7 @@ PassFF.Page = (function () {
 
 // %%%%%%%%%%%%%%%%%%%%%%%%%%% Miscellaneous %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 
-    copyToClipboard: content_function("Page.copyToClipboard", function (text) {
+    copyToClipboard: background_function("Page.copyToClipboard", function (text) {
       document.addEventListener("copy", function oncopy(event) {
         document.removeEventListener("copy", oncopy, true);
         event.stopImmediatePropagation();
```

Could you apply this patch and test it?
Guide to debug PassFF: https://github.com/passff/passff/blob/master/docs/CONTRIBUTING.md

**Comment by treyssatvincent** [comment]
First of all I can reproduce on google and facebook but I don't have this error anywhere (even where you have it).

With the patch it don't copy on the clipboard and it return nothing on the console (I don't have anymore ` [PassFF.content] Message Page.copyToClipboard received in content`).

I think the issue comes from my OS or my browser.

**Comment by 5bentz** [comment]
I cannot reproduce on Arch with Firefox 62 (same behavior as Debian).
Could you test that with a clean Firefox profile? Go to `about:profiles` to do so.

Off-topic: When I enable logging in the JS web console, PassFF does not log as much as expected. Weird.

**Comment by pfheatwole** [comment]
I'm seeing this behavior on Firefox 84.0 (Fedora 33, passff 1.10.4). Trying to copy a login or password produces the console log message `[PassFF.content] Message Page.copyToClipboard received in content`, but nothing is copied.

Looking at [page.js:copyToClipboard](https://github.com/passff/passff/blob/b6f4aced1bd91cbb3733de80fae8f6be69d7b143/src/modules/page.js#L875) it writes to the clipboard using the older `execCommand` method of interacting wtih the clipboard. I'm not an extension developer so I'm clueless on current APIs, but way back in Firefox 63 they added a new "less kludgy" clipboard API: https://blog.mozilla.org/addons/2018/08/31/extensions-in-firefox-63/

Maybe this issue is related to ongoing changes to the clipboard API?

**Comment by tuxor1337** [comment]
@pfheatwole I can't reproduce this on Firefox 84.0 (Fedora 33, passff 1.10.4).
1. Do you use Wayland or X11?
2. Which website are you on when you encounter the problems?
3. Which Firefox extensions are running in parallel that might interfere?

**Comment by tuxor1337** [comment]
With the latest update (passff 1.10.5), the new clipboard API is used. Would you please try to reproduce your issue with 1.10.5 (and answer the three questions above)?

**Comment by pfheatwole** [comment]
Upgrading to 1.10.5 works great, thanks! But some extra info:

Because you failed to replicate the bug I decided to do some extra digging using 1.10.4. Turns out the issue was because in `about:config` I had set `dom.event.clipboardevents.enabled = False`. While still using 1.10.4, setting it to `enabled` fixed the copy issue. Same behavior on both X11 and Wayland.

From https://developer.mozilla.org/en-US/docs/Mozilla/Preferences/Preference_reference/dom.event.clipboardevents.enabled:

> dom.event.clipboardevents.enabled lets **websites** get notifications if the user copies, pastes, or cuts something from a web page, and it lets them know which part of the page had been selected. The emitting of the oncopy, oncut and onpaste events are controlled by this preference.

Emphasis mine on "websites"; doesn't say anything about webextensions so I thought it was safe. Doesn't seem like it should affect passff writing to the clipboard; should I report this a Firefox bug? Or possibly just a documentation bug?

**Comment by tuxor1337** [comment]
Okay, thanks for your response!

Since that doc-page you linked to is not maintained, I don't think a documentation bug is the best way to go. But it might be worth  reporting to Mozilla's Bugzilla that this preference isn't working as expected for you and that you would like to have a better way to fine-tune this setting. You can mention in that report that the (archived) docs are misleading.
