### ISSUE TITLE
Data and password still visible after timeout

### ISSUE THREAD

**Issue by alercunha** [passff/passff#444]
- Versions
  - Operating system: Mint 19 
  - Browser: Firefox 77.0.1
  - PassFF: 1.10
  - Host app: passff-host 1.2.1

Status line output: `[07:56:00] show -> (0) no error message`

---

### Actual behaviour
After a certain period the password store is locked out so next time you try to use it challenges the user for the password-store password. However when using PassFF it's possible to still obtain some data (including passwords) long time after the password-store is locked.

### Expected behaviour
After the password-store is locked no data should be available unless the user enters his password to unlock the password-store.

### Steps to reproduce the behaviour
1. Select any entry
2. Chose 'Display'
3. Close the display pop-up
4. Wait a long time (sorry not sure how long it takes for it to lock again)
5. CTRL+SHIFT+N

The previous pop-up with the entry data (including password) is accessible. If you test opening a new entry the user is challenged for his password so the password-store is locked but still that window is leaking information.

**Comment by tuxor1337** [comment]
Good point!

In fact, Ctrl+Shift+N and Ctrl+Shift+T are pretty naughty Firefox features. Even when you tell Firefox not to create a history, those features are available.

I don't see any way how to deal with this since Firefox stores the page in cache and reloads it from there, right?! How could we possibly interfere?

**Comment by alercunha** [comment]
@tuxor1337 not sure what a solution would be. I'm not very familiar with Firefox extension architecture. Maybe some sort of JS that after a period of time removes the data from that page? Or changing the page to loads its content dynamically during the mouse-over event - so to force the password-store to return the data for each mouse-over?

Maybe a simpler solution could be to have a 'Done' button that clears the data and close the form. So if a user comes back using CTRL+SHIFT+N the page's content is no longer there.

**Comment by tuxor1337** [comment]
Turns out, this issue was avoidable from our side. Fix is in review on addons.mozilla.org

**Comment by alercunha** [comment]
@tuxor1337 can you please post a link to that fix so I can follow up?

**Comment by tuxor1337** [comment]
Fix is in commit https://github.com/passff/passff/commit/be83d11b02ba4ea14998ed6a8b914b71f7d02da1, hotfix release is 1.10.1 (https://github.com/passff/passff/releases/tag/1.10.1), also available from addons.mozilla.org since it has been auto-reviewed a second ago: https://addons.mozilla.org/de/firefox/addon/passff/versions/

**Comment by alercunha** [comment]
This is fantastic. I just upgraded my extension and tested the fix. Not the prettiest solution but definitely gets the job done.
From bug to hotfix in a couple hours, this is highly appreciated, great work!
