### ISSUE TITLE
Asking for gpg password when not trying to decrypt anything

### ISSUE THREAD

**Issue by Iambecomeroot** [passff/passff#454]
### General information. Describe your environment
PassFF is asking me to enter my gpg password when I'm not trying to decrypt anything. I get the normal password prompt dialog, but not trying to log in to anything. It happens if I don't even have firefox focused. I can be in a terminal and get interrupted by it.

I used the PID of the password prompt window to track down the parent process asking for the password.

Parent process of the dialog is:
```
gpg2 -d --quiet --yes --compress-algo=none --no-encrypt-to --batch --use-agent /home/marcel/.password-store/...
```

And parent process of that is:
```
python3 /usr/share/passff/passff.py /usr/lib/mozilla/native-messaging-hosts/passff.json passff@invicem.pro 
```

- Versions
  - Operating system:  Linux Zeus 5.4.66-1-lts #1 SMP Thu, 17 Sep 2020 18:00:06 +0000 x86_64 GNU/Linux
  - Browser: Firefox 81.0
  - PassFF: 1.10.3
  - Host app: 1:1.2.1-3

Status line output: `[hh:mm:ss] ls -> (0) no error message`

- Output of `pass`: I don't want to give this information, but pass from the command line works fine
- Your preferences
  - In PassFF: Defaults
  - In the host app `passff.py`: No modifications
- Messages in the web console: 

---

### Actual behaviour
PassFF is trying to decrypt stuff in the background

### Expected behaviour
PassFF should only decrypt passwords when I'm trying to log in

### Steps to reproduce the behaviour
1. Install community/passff-host on Arch linux
2. Wait until password prompt appears

**Comment by tuxor1337** [comment]
You posted the version of passff-host, you are using. But which version of the PassFF browser extension are you using? Furthermore, please add the information about your PassFF preferences.

**Comment by Iambecomeroot** [comment]
I'm sorry I didn't understand the template. I have updated the issue.

**Comment by tuxor1337** [comment]
No, it's definitely not caused by passff-host because this issue seems to be about PassFF sending undesired requests to passff-host (though I have no idea why it would do it and I can't reproduce it).

**Comment by Xohwie1i** [comment]
Hello, I'm not sure how much I can add to this discussion from a technical perspective. However, I can confirm that I'm getting random password prompts similar to those described here. Also, and I'm not sure if this is related or not, but OTP input also stopped worked for Google logins, now it just enters my email, not the OTP code . Anyway, again, my apologies if this is not helpful.

**Comment by tuxor1337** [comment]
There are only two situations where PassFF would query the password store without direct user interaction:

1. Index URL fields on startup.
2. Auto-fill/auto-submit input fields.

Both of these are deactivated by default in the preferences. Since you say that you use the default preferences, I can't see any reason why you would see random password prompts. Plus, I can't reproduce it.

If PassFF is really randomly querying entries from the password store, this is a severe security issue. I purposely designed it in such a way, that it will (by default) only query the password store after direct user interaction. And that's what is has been doing for me so far.

**Comment by Iambecomeroot** [comment]
Hm. Indexing was actually on. I don't remember changing anything, that's why I said it was all default. Is there a way to confirm that this is the culprit? It's convenient, actually. I was just very suspicious about entering my gpg password without knowing what I was unlocking.

**Comment by tuxor1337** [comment]
If your issue is not reproducible, then there is no way to confirm that this is the culprit. But it most likely is. Indexing might spawn on several occasions, e.g. when Firefox automatically installs an update for the PassFF extension in the background. And there have been two such updates in the last few days. Probably there are other reasons why Firefox would kill and restart the PassFF background process and that would also lead to a re-indexing.
