### ISSUE TITLE
GLOB in URLs

### ISSUE THREAD

**Issue by D4nte** [passff/passff#457]
### General information. Describe your environment
As per the [pass's website](https://www.passwordstore.org/), glob format is suggested:

```
URL: *.amazon.com/*
```

However, when using such format with passff, a warning is displayed saying that the URL could not be parsed and whether we trust the website.

Instead, I propose for passff to support glob :)

- Versions
  - Operating system: Mac OS Catalina 10.15.6
  - Browser: Firefox 81.0.1 
  - PassFF: 1.10.3
  - Host app: Installed via the script, not sure how to get the version

Status line output: `[15:54:52] show -> (0) no error message`

**Comment by tuxor1337** [comment]
What is PassFF supposed to do, when the URL is `*.amazon.com/*` and the user chooses the `Goto` action?

**Comment by D4nte** [comment]
> What is PassFF supposed to do, when the URL is `*.amazon.com/*` and the user chooses the `Goto` action?

Great question.
Do you currently support several `URL` entries? From my experience it doesn't seem to be the case.

Goto the first URL entry that doesn't have a glob.

**Comment by tuxor1337** [comment]
Currently, several lines starting with `url:` will overwrite the field so that the only the last value is used.

**Comment by D4nte** [comment]
> Currently, several lines starting with `url:` will overwrite the field so that only the last value is used.

Interesting, why did you settle for the last value?

**Comment by iinuwa** [comment]
> What is PassFF supposed to do, when the URL is `*.amazon.com/*` and the user chooses the `Goto` action?

Perhaps it could disable the feature for entries that only have glob URLs?

**Comment by D4nte** [comment]
I think it's fine to use the last `url:` entry that does **not** have a glob.

**Comment by xeruf** [comment]
Additionally, this would enable `url: *` for entries that are not specific to a website such as credit card data.

**Comment by tuxor1337** [comment]
Multiple URLs are now supported so that PassFF uses the first URL field that is not an URL. However, if there is only a glob pattern and no valid URL, the go-to-action will attempt to go to the glob URL (which will usually fail).

This means that the glob patterns will at least not break PassFF most of the time. But we cannot support them when looking up matching entries because that would require support for glob patterns, and this is not easily available in standard JavaScript. Note that, in PassFF, we avoid external JS dependencies to avoid security issues.

So, unfortunately, I'm closing this as "won't fix" for now. If you have a suggestion how to support glob patterns without adding external JS dependencies, feel free to reopen or create a PR.
