### ISSUE TITLE
using mozilla nsILoginManager API?

### ISSUE THREAD

**Issue by drzraf** [passff/passff#46]
Shouldn't implementing nsILoginManagerStorage
https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsILoginManager
https://developer.mozilla.org/en-US/docs/Creating_a_Login_Manager_storage_module
... be the right way to integrate with Firerfox password management in an OS-independant and feature-full manner ?

**Comment by gekmihesg** [comment]
Inspired by this project and this thread, I started to implement nsLoginManagerStorage with pass backend here: https://github.com/gekmihesg/pass-manager

It's not very efficient, but it kinda works for FF and TB. The mapping very strict at the moment, but it should be possible to reconstruct some of the required fields from context.

**Comment by josephholsten** [comment]
Is anyone still working on this? Is it worth taking bits from @gekmihesg's impl?

**Comment by jvenant** [comment]
I tried to implement a nsLoginManagerStorage already but couldn't figure out how to do that in a restartless addon.
@gekmihesg addon is not a restartless addon.

I have a branch on my computer with tests about that, but didn't put it on github yet because it's the very beginning and nothing really work. If someone want to check, I can push my branch on github

**Comment by nwallace** [comment]
With the recent rewrite for Web Extensions, this issue is no longer on the table
