### ISSUE TITLE
Login form not autofilled

### ISSUE THREAD

**Issue by chept** [passff/passff#480]
### General information
- Versions
  - Operating system: Debian GNU/Linux 10 (buster)
  - Browser: Mozilla Firefox 78.10.0esr
  - PassFF: 1.10.6
  - Host app: 1.2.1

- Status line output: `[17:32:17] show -> (0) no error message`

- Messages in the web console: 
```
[PassFF.content] 1 matches for https://adherent.aesio.fr/login  
[PassFF.content] Best fit item aesio for https://adherent.aesio.fr/login  
[PassFF.content] Start pref-auto-fill  
[PassFF.content] fillInputs: No relevant login input elements recognized.  
```
- PassFF is configured to autofill and submit forms.

### Actual behaviour
PassFF doesn't autofill the login form (and so, does not submit it), although messages from the console says that the page matches a password entry.
It looks like that the form is loaded using javascript, after PassFF search for it.

### Expected behaviour
The login form should be autofilled. Maybe try or retry to look for the fields after a delay, especially if the page is matched ? 

### Steps to reproduce the behaviour
1. Create the pass entry: `pass generate -f test/aesio`
2. Set passFF to autofill forms. 
3. Refresh passFF
4. Go to https://adherent.aesio.fr/login
5. Observe that the form is not autofilled

**Comment by tuxor1337** [comment]
To be clear: When manually instructing PassFF to fill the form, everything works fine. But the form is not automatically filled because it is only injected into the site after the document has finished loading. I set this issue to "won't fix" because I personally consider the auto-fill feature a security issue in PassFF and don't recommend using it. Hence, I don't want to work on a fix. But if you would like to work on a solution, feel free to open a pull request.

**Comment by chept** [comment]
After reading other issues and playing a bit, I agree with the fact that autofilling can be dangerous, so this issue is not one anymore for me.
