### ISSUE TITLE
Credit card form broken

### ISSUE THREAD

**Issue by xeruf** [passff/passff#483]
Versions: all latest on Arch Linux
<img width="309" alt="image" src="https://user-images.githubusercontent.com/13354331/125680926-8480b105-4a90-4c59-981e-258a1acf9dee.png">
Trying to enter credit card info on https://www.sunday.de/checkout

**Comment by tuxor1337** [comment]
Strictly speaking, the input field is not broken. You can still enter you credit card number.

The problem arises because the website's javascript attempts to dynamically set background properties of the input field. I close this as "won't fix" since this is bad website design and we can't be compatible with all the bad javascript code out there. Feel free to disable the marking of fillable input fields in the PassFF preferences. These kinds of websites are the original reason why I decided to make this feature optional.
