### ISSUE TITLE
firefox extension can't connect to host app in librewolf browser

### ISSUE THREAD

**Issue by linhandev** [passff/passff#506]
### Versions
- Operating system: Arch Linux
- Browser: LibreWolf
- PassFF: 1.13
- Host app: 1.2.3

Status line output: `[hh:mm:ss] show -> (0)`

[02:36:15] ls -> (-1) PassFF failed to execute the host app

### Observations

passff browser extension doesn't seem to work in librewolf browser. I tried to install passff in firefox on the same machine and it works perfectly. librewolf is a fork of firefox. I think this may not be something major. Maybe some of the librewolf's tweaks broke something. It would be really nice if you guys can get it passff to work in librewolf !

---

### Steps to reproduce the issue
1. install passff in librewolf should reproduce the problem

### Actual behaviour

unable to connect to host app

**Comment by JacksonChen666** [comment]
can confirm with host machine running both firefox developer edition and librewolf, it does not work on librewolf but it does on firefox developer edition.

<details><summary>my info of things and logs</summary>

extension version: 1.13
host app: 1.2.3

status line output: `[09:39:17] ls -> (-1) PassFF failed to execute the host app`

logs from console (or debugging messages):
```
09:39:17.765 [PassFF.background] PassFF failed to execute the host app Error: Attempt to postMessage on disconnected port util.js:84:14
    logPrototype moz-extension://c836d243-dca4-4e5b-b861-78ed453eb48e/modules/util.js:84
    executePass moz-extension://c836d243-dca4-4e5b-b861-78ed453eb48e/modules/pass.js:352
    (Async: promise callback)
    executePass moz-extension://c836d243-dca4-4e5b-b861-78ed453eb48e/modules/pass.js:308
    background_function moz-extension://c836d243-dca4-4e5b-b861-78ed453eb48e/modules/util.js:138
    loadItems moz-extension://c836d243-dca4-4e5b-b861-78ed453eb48e/modules/pass.js:376
    background_function moz-extension://c836d243-dca4-4e5b-b861-78ed453eb48e/modules/util.js:138
    init moz-extension://c836d243-dca4-4e5b-b861-78ed453eb48e/modules/pass.js:257
    init_promise moz-extension://c836d243-dca4-4e5b-b861-78ed453eb48e/modules/main.js:164
    (Async: promise callback)
    init moz-extension://c836d243-dca4-4e5b-b861-78ed453eb48e/modules/main.js:164
    (Async: EventListener.handleEvent)
    <anonymous> moz-extension://c836d243-dca4-4e5b-b861-78ed453eb48e/modules/main.js:199
09:39:17.766 [PassFF.background] loadItems failed! util.js:84:14
09:39:17.767 [PassFF.background] Init auth module util.js:84:14
09:39:17.770 [PassFF.background] Awaiting tab init... 3 about:addons util.js:84:14
09:39:17.771 [PassFF.background] Tab init done 3 about:addons util.js:84:14
09:39:18.658 [PassFF.background] Awaiting tab init... 10 about:devtools-toolbox?id=passff%40invicem.pro&type=extension util.js:84:14
09:39:18.659 [PassFF.background] 0 matches for about:devtools-toolbox?id=passff%40invicem.pro&type=extension 2 util.js:84:14
09:39:18.662 [PassFF.background] Tab init done 10 about:devtools-toolbox?id=passff%40invicem.pro&type=extension util.js:84:14
```

</details>

### solution: do the [host installation](https://github.com/passff/passff-host#installation) again, but for `librewolf` instead of `firefox` with the last word of the command.

<details><summary>me figuring things out (somewhat relevant to solution)</summary>

i try to see what's happening. so i try sending a native message with a port of `/bin/echo` (yeah i had no idea what i was doing... yet).
it fails, then i try echo.
now looking over the [passff-host][psf] repo. then i realize something: there's a folder for native messaging (after poking around.
it might be possible that librewolf does not read the appropriate folder for sending native messages, which results in the extension not working.
is there a folder for librewolf with native messaging thing? no.
i'm not sure where to go to put that host script for librewolf. but what if i execute the script again?

i executed this:

`curl -sSL github.com/passff/passff-host/releases/latest/download/install_host_app.sh | bash -s -- /Applications/LibreWolf.app/Contents/MacOS/librewolf`

outputs

```
Usage: bash [OPTION] [chrome|chromium|firefox|opera|vivaldi|librewolf]

  Example:
    bash firefox   # Install host app for Mozilla Firefox

  Options:
    -l, --local    Install files from disk instead of downloading them
    -h, --help     Show this message
```

oh.... so there's a librewolf option for installation? didn't know, could've been useful to add note.
executing `curl -sSL github.com/passff/passff-host/releases/latest/download/install_host_app.sh | bash -s -- librewolf`, it does it's thing.
re-enable the extension **and it works now**

</details>

[psf]: https://github.com/passff/passff-host#latest-from-github

**Comment by tuxor1337** [comment]
Support for `librewolf` is now explicitly mentioned in the README: https://github.com/passff/passff-host/commit/503bfeb04e9f3f95fb0cd8422814d6aa291458ff
