### ISSUE TITLE
Make keyboard shortcut field case insensitive

### ISSUE THREAD

**Issue by bkazez** [passff/passff#536]
### Versions
- Operating system: macOS 13.4 (22F66)
- Browser: 114.0.2 (64-bit)
- PassFF: 1.14.1
- Host app: 

Status line output: [18:37:44] show -> (0) no error message

### Steps to reproduce the issue
1. Open passff preferences in Firefox
2. Type a new keyboard shortcut with lowercase letters
3. Close passff preferences

### Actual behaviour
The shortcut doesn't stick - it reverts back to what it was before

### Expected behaviour
The shortcut should stick and the case should be normalized.

**Comment by tuxor1337** [comment]
Thanks for the report! As an example, try setting it to "ctrl+alt+u" and it will not have any effect. When reloading the preferences page, the field will be reset to its previous value. This can be fixed in https://github.com/passff/passff/blob/2f3fb4476cabe8715472ee5807607887d758dfc1/src/modules/preferences.js#L215-L232 by making all the checks case insensitive.

**Comment by bkazez** [comment]
By the way, how fancy can plugins get on their prefs pages? Without doing a native companion app, could you have a little shortcut selection widget like this? It would remove the need for documentation and parsing user input.

<img src="https://github.com/passff/passff/assets/64005/22e27038-b1f1-4952-a7ad-a42d78c319a6" srcset="https://github.com/passff/passff/assets/64005/df2fc5e1-0992-43b9-8747-e759ca7014b9 2x" alt="Example Image">
