### ISSUE TITLE
Allow configuration as for what to post where

### ISSUE THREAD

**Issue by ct-clearhaus** [passff/passff#61]
E.g. AWS console (AMI) login wants account name and user name (along with password and OTP). It'd be nice if we could have a password file like:

```
the-password
login: my-user-name
fields:
  - account: my-account-name
```

Also, I use a site where the user name field has `name="69"` for some weird reason. With the above one could have the file like:

```
the-password
login: my-user-name
fields:
  - 69: my-user-name
  - 76: the-password
```

... since the password field has `name="76"`. So basically a way to specify what goes where.

**Comment by ct-clearhaus** [comment]
Could also be nice to mark e.g. "remember me" checkboxes.

**Comment by sometoby** [comment]
Seems to be the same as #75. I think this is a feature that PassFF definitely should have.

**Comment by nwallace** [comment]
I think this is different from #75.  I think #75 would be for things that you'd reuse across multiple sites (like addresses or credit card info), whereas this issue is about site-specific overrides.

I agree, I think site-specific overrides are really important, and shouldn't be hard to implement. This, along with improving the search/URL-match algorithm, is one of my top priorities for the next release. I'll keep you updated.

In the meantime, any thoughts on the suggested file format?

@ct-clearhaus suggested this:
```
the-password
username: the-username
fields:
  - account: my-account-name
```

But we could just do this:
```
the-password
username: the-username
account: my-account-name
```

Any thoughts? I'm personally not sure which I prefer. The former gives you more control, but the latter has a higher likelihood or just working&trade; with people's password files as they already exist

**Comment by ct-clearhaus** [comment]
@nwallace I like the simplicity of avoiding `fields:`. The only reason that I can come up with is that everything becomes a keyword that is posted, and perhaps that's surprising? I mean, rather post too little than too much.

It's adding syntax constraints to file; also, notice the alternative "subfolder strategy" mentioned on https://www.passwordstore.org/#organization. With both of our suggestions

> (...) you have the freedom of choosing the one that fits your workflow best.

is not true anymore — if it should work with passff. However, one has to configure it *somehow*, so I'm all up for any of the two 🙂

**Comment by tuxor1337** [comment]
@ct-clearhaus Isn't this already implemented in the latest version from addons.mozilla.org? See also https://github.com/passff/passff/blob/master/src/modules/form-helper.js#L156. An entry like this would enter `my-account-name` into text inputs of name or id `account`:

    the-password
    username: the-username
    account: my-account-name

I tested it on a toy example and it worked for me. If it doesn't work for you, please reopen.
