### ISSUE TITLE
Form fill profiles

### ISSUE THREAD

**Issue by marxjohnson** [passff/passff#75]
Lastpass has a feature called "Form Fill Profiles".  It allows you to set values for common fields on web forms (Such as address lines, credit card info) and have them automatically filled by the browser extension, just like it fills in login forms.

It would be cool if passff could do the same thing, perhaps using a specially constructed multiline file in your password store.

A couple of possibilities I can think of:

1.
The file contains 1 field per line, in the format
`fieldname,alternativefieldname1,alternativefieldname2|value`
For example, a line could read
`zip,zipcode,postcode|NW1 1AA`
Selecting a file in the browser extension could offer, along with "Fill", "Fill and Submit" etc, "Fill Form Profile".  For each line, it finds the first field matching a possible field name and fills it.

2.
The file contains 1 field per line, in the format
`FieldName|value`
For example, a line could read
`PostalCode|NW1 1AA`
The configuration interface for the extension could then be extended, so as well as allowing field names for username as password to be configured, field names for a step of standard form fields could be configured.
A "Form Fill Profile" option could be added as in possibility 1.  Instead of taking the field names from the file, it takes them from the extension's configuration.

**Comment by marxjohnson** [comment]
I just spotted that the current "Fields Parameters" setting contains an option for a "Url" field.  Does that already do something like I'm describing?

**Comment by jvenant** [comment]
Hi Mark,

Thank you for your feedback.

The url field (in your password file) is used to go to the login form.

Concerning your feature request, I'm not very comfortable with it.
I mean : it's definitely a nice feature to have, but it also a little bit out of the scope of this addon.
And it's also tedious to implement to have something useful because there are so many cases of form, input and fieldname on the web.
For example : 
* some website has one input for the name and some other one for the first name and one for the last name
* Credit card field can also be on multiple inputs or on one input. Separated by space or not.
and so on

Concerning the format proposition, It think it's too complicated. Most of the people won't do the effort to use it. 
We are here on a pass script (kiss philosophy) limitation : it don't manage structured data. Pass is about storing encrypted passwords. Not encrypted data. Some people on the pass ml talked about adding some kind of "plugin" mechanism to manage structured data, but nothing has been done yet.

So to resume : Nice feature but
* A little bit out of the scope (of the Firefox addon and of the pass script)
* Too complicated to implement to have something useful (too many different web forms)
* Too complicated to use (too many configuration stuff)

I keep it as an enhancement any way to see other user reaction about this.

**Comment by marxjohnson** [comment]
Hi John,
Thanks for your feedback, I appreciate why you think this is out of scope for the project.  I'll keep an eye on future developements.

**Comment by metabubble** [comment]
I think using enriched password files that also carry the input field's name may be a wonderful way to provide support for the most complex password entry dialogues.

**Comment by tuxor1337** [comment]
@metabubble Password files that also carry the input field's name have been supported for a while: https://github.com/passff/passff/issues/61#issuecomment-352145275

@marxjohnson I suppose this does not solve this issue for you. Do I understand correctly that you wish PassFF would automagically fill in address forms etc.?

**Comment by tuxor1337** [comment]
Closing this, since I think that a more sophisticated autofill feature is out of scope for this extension.

**Comment by chmduquesne** [comment]
I am a bit sad to see this rejected. Personally, I think this would have a lot of value!

Personally, I do not see this as breaking the KISS principle, but more as an advanced use of a very flexible tool.

Any other way this could be done? If you don't want the addon to take responsibility for the form-filling, maybe we could have a special field

    formfiller: /path/to/script.js

This script could be executed whenever the field is there.

Just throwing some ideas...
